[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm ci --legacy-peer-deps']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run preview -- --host 0.0.0.0 --port $PORT'

[variables]
PORT = '3000'